# Generated by Django 4.1 on 2022-09-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome_exibicao', models.CharField(max_length=255, null=True)),
                ('endereco', models.CharField(max_length=255, null=True)),
                ('bairro', models.CharField(max_length=255, null=True)),
                ('cidade', models.CharField(max_length=255, null=True)),
                ('valor', models.FloatField()),
                ('m2_construido', models.IntegerField()),
                ('m2_total', models.IntegerField()),
                ('dormitorios', models.IntegerField()),
                ('suites', models.IntegerField()),
                ('vagas', models.IntegerField()),
                ('area_servico', models.BooleanField()),
                ('churrasqueira', models.BooleanField()),
                ('piscina', models.BooleanField()),
                ('area_gourmet', models.BooleanField()),
                ('descricao', models.TextField()),
                ('foto_1', models.ImageField(upload_to='')),
                ('foto_2', models.ImageField(upload_to='')),
                ('foto_3', models.ImageField(upload_to='')),
                ('foto_4', models.ImageField(upload_to='')),
                ('video', models.ImageField(upload_to='')),
            ],
        ),
    ]
