# Generated by Django 4.1 on 2022-09-08 17:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casa',
            name='data_cadastro',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 8, 17, 32, 54, 455884, tzinfo=datetime.timezone.utc)),
        ),
    ]
