# Generated by Django 4.1 on 2022-09-08 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0002_casa_data_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casa',
            name='data_cadastro',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 8, 17, 34, 38, 120420, tzinfo=datetime.timezone.utc)),
        ),
    ]
