# Generated by Django 4.1.1 on 2022-09-09 00:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0003_alter_casa_data_cadastro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casa',
            name='foto_1',
        ),
        migrations.RemoveField(
            model_name='casa',
            name='foto_2',
        ),
        migrations.RemoveField(
            model_name='casa',
            name='foto_3',
        ),
        migrations.RemoveField(
            model_name='casa',
            name='foto_4',
        ),
        migrations.RemoveField(
            model_name='casa',
            name='video',
        ),
        migrations.AddField(
            model_name='casa',
            name='foto',
            field=models.ImageField(default=0, upload_to='static/images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='casa',
            name='data_cadastro',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 9, 0, 30, 11, 117224, tzinfo=datetime.timezone.utc)),
        ),
    ]
