# Generated by Django 4.1 on 2022-09-15 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0004_remove_casa_foto_1_remove_casa_foto_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casa',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casa',
            name='lng',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='casa',
            name='data_cadastro',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 15, 17, 34, 59, 32989, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='casa',
            name='foto',
            field=models.ImageField(upload_to='imoveis/static/images'),
        ),
    ]
