# Generated by Django 4.1 on 2022-09-15 18:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0005_casa_lat_casa_lng_alter_casa_data_cadastro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casa',
            name='data_cadastro',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 15, 18, 17, 14, 614217, tzinfo=datetime.timezone.utc)),
        ),
    ]
