# Generated by Django 4.1 on 2022-09-15 18:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0006_alter_casa_data_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casa',
            name='data_cadastro',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 15, 18, 42, 19, 697806, tzinfo=datetime.timezone.utc)),
        ),
    ]
