# Generated by Django 4.1.1 on 2022-09-16 01:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0007_alter_casa_data_cadastro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casa',
            old_name='foto',
            new_name='foto1',
        ),
        migrations.RemoveField(
            model_name='casa',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='casa',
            name='lng',
        ),
        migrations.AddField(
            model_name='casa',
            name='foto2',
            field=models.ImageField(default=0, upload_to='imoveis/static/images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casa',
            name='foto3',
            field=models.ImageField(default=0, upload_to='imoveis/static/images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casa',
            name='foto4',
            field=models.ImageField(default=0, upload_to='imoveis/static/images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='casa',
            name='data_cadastro',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 16, 1, 38, 42, 724779, tzinfo=datetime.timezone.utc)),
        ),
    ]
