# Generated by Django 4.1.1 on 2022-09-16 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0008_rename_foto_casa_foto1_remove_casa_lat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cota',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=140)),
                ('administradora', models.CharField(max_length=140)),
                ('valor', models.CharField(max_length=140)),
                ('entrada', models.CharField(max_length=140)),
                ('parcelas', models.CharField(max_length=140)),
                ('segmento', models.CharField(max_length=140)),
                ('vencimento', models.CharField(max_length=140)),
                ('img', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='casa',
            name='data_cadastro',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 16, 16, 16, 3, 796846, tzinfo=datetime.timezone.utc)),
        ),
    ]
